Review
esa-prl/simple_rover_locomotion pull request #1
Opened 2020-06-24 12:57 UTC by mvoellmy

Once the code review is done, change the base branch from `empty` to `master` and merge the changes.

2020-10-07 14:32 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    centre_of_rotation_y = 0;
No, this covers the case where the two center wheels are non steerable. Thus the center of rotation_x is moved to align with the driving axis of the center wheels.

2020-10-07 16:04 UTC, mvoellmy commented on include/simple_rover_locomotion/simple_rover_locomotion.hpp
> +  // bool enable();
done

2020-10-07 16:10 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +          (sin(alpha + beta) * x_dot - cos(alpha + beta) * y_dot - l * cos(beta) * theta_dot) / r;
While this looks true, I prefer to leave it as is as this corresponds with the calculations presented in the /doc/ directory.
![image](https://user-images.githubusercontent.com/10925797/95357574-5061cc00-08c8-11eb-8038-592cc823fba3.png)

2020-10-07 16:13 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    steering_msg.header.stamp = clock->now();
I think we had this conversation a few times in the lab and (I think) we agreed that we'll leave the head in the jointcommand? Now thinking about it again, I think it makes sense to have the header in case we ever want to send an individual jointcommand topic. Do you remember our discussions and the resolution from then?

2020-10-07 16:24 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      } else {
Yeah definitely! :+1:

2020-10-08 11:06 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +  RCLCPP_INFO(this->get_logger(), "SimpleRoverLocomotion started.");
Removed it since it is duplicate with the output msg from locomotion_mode.cpp constructor

2020-10-08 11:13 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      // printf("beta_steer 180    : %f\n",beta_steer*180/M_PI);
done

2020-10-08 11:24 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +        r = cyl->radius;
This does not compile. The base class "geometry" does not have a field radius as the geometry fields are only defined when inherited by the a shape class such as box, cylinder, mesh or sphere see (http://mirror-ap.docs.ros.org/diamondback/api/urdf/html/classurdf_1_1Geometry.html). I assume at compile time it is not known what the link geometry of the link is and thus it needs to be defined explicitly as a cylinder.

2020-11-19 08:28 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    y_dot = 0.0;
addressed in a TODO: comment

2020-11-19 08:56 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +
Done.

2020-11-19 08:57 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +  }
Checks now like this:
```
    if (!leg->steering_motor->joint)
```

2020-11-19 08:58 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      non_steerable_legs[1]->steering_motor->global_pose.position.y) / 2;
Done

2020-11-19 09:01 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      beta_steer = beta_current;
@wieset It is possible to send a velocity command to a steering joint?

2020-11-19 09:10 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      l = sqrt(pow(offset_str_position_x, 2.0) + pow(offset_str_position_x, 2.0));
@wieset Looked into it. Even though in most cases x*x*x... is better, pow(x, 2) has the same performance as x*x. Can still change it if you prefer it x*x.

https://baptiste-wicht.com/posts/2017/09/cpp11-performance-tip-when-to-use-std-pow.html

2020-11-19 09:11 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      // TODO: Could implment this into main LocomotionMode class and add a field wheel diameter. Also make sure the wheel link is a cylinder.
Done.

2020-11-19 09:12 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    int adjustment_count = 0;
Done.

2020-11-19 09:13 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +        flip_velocity = !flip_velocity;
Done.

2020-11-19 09:13 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +        beta_steer = beta_steer + M_PI;
Done.

2020-11-19 09:26 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +      }
Move it in front of which position limiting exactly?

2020-11-19 09:30 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    }
Done.

2020-11-19 10:29 UTC, mvoellmy commented
Implemented the most important changes. Moved the open points into the CHANGELOG.

2020-11-19 23:12 UTC, wieset requested changes

2020-11-19 23:13 UTC, wieset approved these changes

2020-11-20 13:10 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
> +    if (!leg->steering_motor->joint)
Done.

2020-11-20 13:19 UTC, mvoellmy commented on src/simple_rover_locomotion.cpp
>  // }
https://github.com/esa-prl/locomotion_mode/pull/1/files#r527685018

2020-11-20 13:22 UTC, mvoellmy commented on include/simple_rover_locomotion/simple_rover_locomotion.hpp
> +  double centre_of_rotation_y_;
Done.

2020-11-20 14:45 UTC, wieset commented on src/simple_rover_locomotion.cpp
>  // }
My bad, didn't spot it in locomotion_mode! All good.

2021-01-07 18:15 UTC, merged